version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data source
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez / we have one row for product_id found in each order_id.
        columns:
          - name: orders_id 
          - name: pdt_id
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"

      - name: product
        identifier: raw_gz_product
        description: product of greenweez with price / we have one row for product_id with price.
        columns:
          - name: products_id
            tests:
              - unique
              - not_null
                  
      - name: ship
        identifier: raw_gz_ship
        description: ship of greenweez customer's order / we have one row for shipping fee found in each order_id.
        columns:
          - name: orders_id
            tests:
              - unique
              - not_null
              
              